services:

  grafana:
    image: grafana/grafana:latest
    container_name: sopes1-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - sopes1-net
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:8
    container_name: sopes1-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sopes1-net

volumes:
  grafana-data:

networks:
  sopes1-net:
    driver: bridge
    name: sopes1-net